# Generated by Django 3.2.3 on 2021-05-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='placeholder.jpeg', upload_to='img'),
            preserve_default=False,
        ),
    ]
